[feat] ci: Adjustments to nginx-fpm-prod

diff --git a/nginx-fpm-prod/entrypoint b/nginx-fpm-prod/entrypoint
--- a/nginx-fpm-prod/entrypoint
+++ b/nginx-fpm-prod/entrypoint
@@ -1,6 +1,15 @@
 #!/bin/sh
 set -e
 
+if [ "$ENABLE_XDEBUG" == "true" ]; then
+  docker-php-ext-enable xdebug >> /dev/null 2>&1
+
+  if [ $? != "0" ]; then
+    echo "[ERROR] An error happened enabling xdebug"
+    exit 1
+  fi
+fi
+
 # Run as current user
 CURRENT_USER=${ASUSER:-${UID:-0}}
 if [ ! -z "$CURRENT_USER" ] && [ "$CURRENT_USER" != "0" ]; then
